kdeldycke/workflows

- .github/workflows/changelog.yaml
- .github/workflows/lint.yaml
- changelog.md
Ready to be merged into `main` branch and then tagged as a new release.
[Auto-generated on run `#1584363461`](https://github.com/kdeldycke/workflows/actions/runs/1584363461) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/42ff72b81dd7046e67b7fe8780792d5c16351043/.github/workflows/changelog.yaml) workflow.
> [changelog] Release v0.2.0

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/lint.yaml
- changelog.md
Ready to be merged into `main` branch and then tagged as a new release.
[Auto-generated on run `#1587939059`](https://github.com/kdeldycke/workflows/actions/runs/1587939059) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/6025f6ccd7b08180232d6643e34c586f67925672/.github/workflows/changelog.yaml) workflow.
> [changelog] Release v0.3.0

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/lint.yaml
- changelog.md
Ready to be merged into `main` branch and then tagged as a new release.
[Auto-generated on run `#1596087109`](https://github.com/kdeldycke/workflows/actions/runs/1596087109) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/7636812ea95010aed136d8f18a214944240e45e2/.github/workflows/changelog.yaml) workflow.
> [changelog] Release v0.3.1

- .github/workflows/changelog.yaml
- changelog.md
> [Auto-generated on run `#1653936673`](https://github.com/kdeldycke/workflows/actions/runs/1653936673) by `autofix-typo` job from [`docs.yaml`](https://github.com/kdeldycke/workflows/blob/a3e7d04820b7cc0a3042c574c2f22bf0d9671bc6/.github/workflows/docs.yaml) workflow.
</details>
> [autofix] Typo

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.5.0` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/637fb80e385742c5c8bfdfb8d0a8f28aae2660db/.github/workflows/release.yaml).
> [Auto-generated on run `#1658839303`](https://github.com/kdeldycke/workflows/actions/runs/1658839303) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/637fb80e385742c5c8bfdfb8d0a8f28aae2660db/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.5.0

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.5.1` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/356a72070ebfac36b83d9ef976c7ea09639bb781/.github/workflows/release.yaml).
> [Auto-generated on run `#1658985208`](https://github.com/kdeldycke/workflows/actions/runs/1658985208) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/356a72070ebfac36b83d9ef976c7ea09639bb781/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.5.1

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.5.2` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/d04996196e3f4a650d3a4b545f87201576517d50/.github/workflows/release.yaml).
> [Auto-generated on run `#1659646007`](https://github.com/kdeldycke/workflows/actions/runs/1659646007) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/d04996196e3f4a650d3a4b545f87201576517d50/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.5.2

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.5.3` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/703ef181c56775ee68204142530b5cf34e14ebaf/.github/workflows/release.yaml).
> [Auto-generated on run `#1659725986`](https://github.com/kdeldycke/workflows/actions/runs/1659725986) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/703ef181c56775ee68204142530b5cf34e14ebaf/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.5.3

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.5.4` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/dc88b7a4e9f35be812d376a84ae2148d1464ef4e/.github/workflows/release.yaml).
> [Auto-generated on run `#1659828401`](https://github.com/kdeldycke/workflows/actions/runs/1659828401) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/dc88b7a4e9f35be812d376a84ae2148d1464ef4e/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.5.4

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.5.5` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/7fad96de62febb6a878c9e04c3bea166344c54ef/.github/workflows/release.yaml).
> [Auto-generated on run `#1668065431`](https://github.com/kdeldycke/workflows/actions/runs/1668065431) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/7fad96de62febb6a878c9e04c3bea166344c54ef/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.5.5

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labeller-file-based.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.6.0` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/88bab0deffaf358fc8eeda4885a91c67d85b2b28/.github/workflows/release.yaml).
> [Auto-generated on run `#1671962084`](https://github.com/kdeldycke/workflows/actions/runs/1671962084) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/88bab0deffaf358fc8eeda4885a91c67d85b2b28/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.6.0

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labeller-file-based.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.6.1` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/13c8039de5ee77d21013b740edbf4384254b2e05/.github/workflows/release.yaml).
> [Auto-generated on run `#1671981205`](https://github.com/kdeldycke/workflows/actions/runs/1671981205) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/13c8039de5ee77d21013b740edbf4384254b2e05/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.6.1

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labeller-file-based.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.6.2` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/3f7ea67d88843f3bc1518782def063b5cdd7b23b/.github/workflows/release.yaml).
> [Auto-generated on run `#1673978442`](https://github.com/kdeldycke/workflows/actions/runs/1673978442) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/3f7ea67d88843f3bc1518782def063b5cdd7b23b/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.6.2

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labeller-file-based.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.6.3` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/a624d047d1e98f6d81762a27ea6f1e62392cd6fd/.github/workflows/release.yaml).
> [Auto-generated on run `#1674111306`](https://github.com/kdeldycke/workflows/actions/runs/1674111306) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/a624d047d1e98f6d81762a27ea6f1e62392cd6fd/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.6.3

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labeller-file-based.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.7.0` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/4c084ceb3cd96818ce142437e840d6da7cbf4492/.github/workflows/release.yaml).
> [Auto-generated on run `#1674381473`](https://github.com/kdeldycke/workflows/actions/runs/1674381473) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/4c084ceb3cd96818ce142437e840d6da7cbf4492/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.7.0

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labeller-file-based.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.7.1` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/fd6d23c4e5b28d837c5c9749acc8dd756af3823f/.github/workflows/release.yaml).
> [Auto-generated on run `#1674400204`](https://github.com/kdeldycke/workflows/actions/runs/1674400204) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/fd6d23c4e5b28d837c5c9749acc8dd756af3823f/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.7.1

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labeller-file-based.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.7.2` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/535e2a59d081925b9497c796c6fbada5a422ec7e/.github/workflows/release.yaml).
> [Auto-generated on run `#1674478368`](https://github.com/kdeldycke/workflows/actions/runs/1674478368) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/535e2a59d081925b9497c796c6fbada5a422ec7e/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.7.2

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labeller-file-based.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.7.3` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/acdfc4bc92644cdaa69cd1c2c869ea12adae6fb0/.github/workflows/release.yaml).
> [Auto-generated on run `#1675007725`](https://github.com/kdeldycke/workflows/actions/runs/1675007725) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/acdfc4bc92644cdaa69cd1c2c869ea12adae6fb0/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.7.3

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labeller-file-based.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.7.4` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/0e8da4825eeb022f788034638c4a3994517a4d55/.github/workflows/release.yaml).
> [Auto-generated on run `#1675037189`](https://github.com/kdeldycke/workflows/actions/runs/1675037189) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/0e8da4825eeb022f788034638c4a3994517a4d55/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.7.4

- .github/workflows/autofix.yaml
- .github/workflows/changelog.yaml
- .github/workflows/docs.yaml
- .github/workflows/labeller-file-based.yaml
- .github/workflows/labels.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- changelog.md
1. creation of a `v0.7.5` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/b82ea00b96357dbcd68ba291b9467a2784bcefcd/.github/workflows/release.yaml).
> [Auto-generated on run `#1675055700`](https://github.com/kdeldycke/workflows/actions/runs/1675055700) by `prepare-release` job from [`changelog.yaml`](https://github.com/kdeldycke/workflows/blob/b82ea00b96357dbcd68ba291b9467a2784bcefcd/.github/workflows/changelog.yaml) workflow.
</details>
> Release v0.7.5

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.10.0` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/648d5b904d4ded65220b3be890bfb05a5ab4defd/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4268941575), to refresh the release date to today …
> Release `v2.10.0`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.11.0` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/96dba44f01c75057ed3f859ac9ec7529958ad361/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4321186171), to refresh the release date to today …
> Release `v2.11.0`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.11.1` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/3012f9ddd0d07ef56a4226abdb2abc3dc7cc4b58/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4335047912), to refresh the release date to today …
> Release `v2.11.1`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.12.0` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/0c33749afb1fecd840d0f3351aa18c6f58325e72/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4336087602), to refresh the release date to today …
> Release `v2.12.0`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.12.1` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/8a2ba011742784841176d6c1bfd2e5558457814d/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4336166545), to refresh the release date to today …
> Release `v2.12.1`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.12.2` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/46f394932a31e0526ba10883f4a05bcb6870c66d/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4351028648), to refresh the release date to today …
> Release `v2.12.2`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.12.3` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/85bef3e6aaae6d393e695983b9334c832cb41f4a/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4529004153), to refresh the release date to today …
> Release `v2.12.3`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.13.0` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/cb16f428e80d501589cac2b9a8631ad3758e2081/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4552458962), to refresh the release date to today …
> Release `v2.13.0`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.13.1` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/3372eac87af4a6dcdd70dffc9d2cf241928c685d/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4604186151), to refresh the release date to today …
> Release `v2.13.1`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.13.2` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/bc421f65ea18dd3bd360403abf7e18af4513a0b5/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4636046541), to refresh the release date to today …
> Release `v2.13.2`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.13.3` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/9ba2aa982e7798b30b55a3fdc8edcefdb9e3614a/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4772798494), to refresh the release date to today …
> Release `v2.13.3`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.13.4` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/a014f6474854ab0f6dc86faefb6fde28795f6971/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4777716977), to refresh the release date to today …
> Release `v2.13.4`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.13.5` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/46e3e73e35f14b3eac44a3920fbcc45cd692db0e/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4861113385), to refresh the release date to today …
> Release `v2.13.5`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.14.0` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/36c1688747267e8675a2cf6db6ff8067edb645b3/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4879535568), to refresh the release date to today …
> Release `v2.14.0`

- .bumpversion.cfg
- changelog.md
1. creation of a `v2.14.1` tag on [`main`](https://github.com/kdeldycke/workflows/tree/main) branch
[^1]: as [defined by `release.yaml`](https://github.com/kdeldycke/workflows/blob/10ab967504490003001385f5e9324fab5ad4f61e/.github/workflows/release.yaml).
1. **click `Re-run all jobs`** from the [workflow run](https://github.com/kdeldycke/workflows/actions/runs/4881889185), to refresh the release date to today …
> Release `v2.14.1`

- .github/update_changelog.py
- .github/workflows/changelog.yaml
- .github/workflows/release.yaml
- changelog.md
- requirements.txt
Refs:
- https://github.com/callowayproject/bump-my-version/issues/15
- https://github.com/callowayproject/bump-my-version/pull/23
> Test upcoming `bump-my-version` `v0.6.0`

- .github/metadata.py
- .github/update_changelog.py
- .github/update_mailmap.py
- .github/workflows/autofix.yaml
- .github/workflows/lint.yaml
- .github/workflows/release.yaml
- .mailmap
- changelog.md
- readme.md
Specifically:
s/anoying/annoying/;
s/artifficially/artificially/;
s/attachement/attachment/;
s/commiters/committers/;
s/dependeing/depending/;
s/doen't/doesn't/;
s/dowload/download/;
s/Dynamiccaly/Dynamically/;
s/emptry/empty/;
s/enought/enough/;
s/gihtub/github/;
s/Graphiz/Graphviz/;
s/invokation/invocation/;
s/precautionnary/precautionary/;
s/Prefered/Preferred/;
s/reuseability/reusability/;
s/sesssion/session/;
s/targetted/targeted/;
s/thouroughly/thoroughly/;
s/upcomming/upcoming/;
s/wofklow/workflow/;
> Fix various typos

- .github/workflows/release.yaml
> Fix pyflakes issues in `release.yaml`

- .github/metadata.py
> Fix typo in metadata.py

- .github/update_mailmap.py
I've run it locally, and it works as expected
> feat: Remove extra git call in `update_mailmap.py`
